apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-helm-dev
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: https://github.com/agasheh2023/argocd.git
    targetRevision: main
    path: gitops-playground/apps/app-helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
